### PR TITLE
Extend portability

### PR DESCRIPTION
**Pull request by mdavidsaver**
Support and test for non-Linux targets.  Adds testing for OSX, various RTEMS versions, and Windows.

Will use `poll()` instead of `select()` except for old windows, old RTEMS, and vxworks.

Also updates GHA configuration.

### CODE REVIEW

**Comment by mdavidsaver** [comment]
```
  testtcp.tap ......... 
  not ok  2 - client greeting 0==8
  not ok  3 - msgid==0x0001
  not ok  4 - buf.c_greet.version==0
  not ok  5 - buf.c_greet.type==0
  not ok  8 - shSendAll(&sock, &buf.bytes, sizeof(buf.s_greet), 0)==1
  not ok 10 - ret==4
  not ok 11 - msgid==0x0005
  not ok 12 - casterSendPHead(&sock, 0x8002, sizeof(buf.ping))==1
  not ok 13 - shSendAll(&sock, &buf.bytes, sizeof(buf.ping), 0)==1
  not ok 14 - casterRecvPMsg(&sock, &msgid, &buf.bytes, sizeof(buf.bytes), 0)==sizeof(buf.ping)
  not ok 15 - msgid==0x0002
  not ok 16 - buf.ping.nonce==htonl(0x10203040)
```

This might have something to do with use of `select()`.  Which will also cause problems with RTEMS 5 cf. https://github.com/epics-base/epics-base/issues/300 .  However, I think `select()` is the only option with RTEMS 4.

**Comment by shroffk** [comment]
While you work on the CI... I can state that I was able to build an IOC with reccaster and succesfully run it ( which is progress from where I was yesterday :) )

```
C:\git\epics\IOCs\cf-test>caget TST{IOC:cf-test}RecSyncMsg-I
TST{IOC:cf-test}RecSyncMsg-I   Initializing
```

**Comment by mdavidsaver** [comment]
Ok, I think I have the tests straightened out.  @shroffk Can you try testing to see if an IOC will sync?

**Comment by mdavidsaver** [comment]
@shroffk Updated based on today's testing.

**Comment by shroffk** [comment]
Thanks, 
I tested the latest changes and van verify the win32 fixes are working as needed.

**Pull request merged**
